version: '3'
services:
  postgres:
    image: postgres
    container_name: civil-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: 12345678
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: